version: "2"

run:
  timeout: 3m
  tests: true
  allow-parallel-runners: true
  go: "1.25.8"

formatters:
  enable:
    - goimports
    - gofmt

linters:
  enable:
    - asciicheck
    - bodyclose
    - cyclop
    - dupl
    - decorder
    - errcheck
    - exhaustive
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - govet
    - ineffassign
    - loggercheck
    - mnd
    - musttag
    - nestif
    - perfsprint
    - revive
    - staticcheck
    - testifylint
    - tparallel
    - unparam
    - unused
    - usetesting
    - wrapcheck
    - whitespace
    - wsl_v5

  settings:
    cyclop:
      max-complexity: 10

    exhaustive:
      default-signifies-exhaustive: true

    funlen:
      lines: 90

    revive:
      rules:
        - name: exported
          disabled: true

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - funlen
      - path: internal/api/rest/handler/
        linters:
          - dupl
      - path: internal/api/grpc/handler/
        linters:
          - dupl
